// <auto-generated />
using System;
using Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240505034039_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.BankFormat", b =>
                {
                    b.Property<int>("BankFormatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankFormatId"));

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slogan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BankFormatId");

                    b.ToTable("BankFormat");

                    b.HasData(
                        new
                        {
                            BankFormatId = 1,
                            Logo = "https://i.pinimg.com/originals/5a/55/9d/5a559d02bc8996d233ba05d8fb2d56e3.png",
                            Name = "BBVA Frances",
                            Slogan = "Creando Oportunidades"
                        },
                        new
                        {
                            BankFormatId = 2,
                            Logo = "https://iconape.com/wp-content/files/ko/182549/png/182549.png",
                            Name = "Grupo Galicia",
                            Slogan = "Te merecés lo mejor, hacete Galicia"
                        },
                        new
                        {
                            BankFormatId = 3,
                            Logo = "https://companieslogo.com/img/orig/BMA-99c2b89d.png?t=1684228585",
                            Name = "Banco Macro",
                            Slogan = "Pensá en grande. Pensá en Macro"
                        },
                        new
                        {
                            BankFormatId = 4,
                            Logo = "https://1000marcas.net/wp-content/uploads/2020/07/Logo-ICBC.png",
                            Name = "ICBC",
                            Slogan = "ICBC, si ;)"
                        });
                });

            modelBuilder.Entity("Domain.Entities.BatchCard", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchId"));

                    b.Property<int>("BankFormatId")
                        .HasColumnType("int");

                    b.HasKey("BatchId");

                    b.HasIndex("BankFormatId");

                    b.ToTable("BatchCard");

                    b.HasData(
                        new
                        {
                            BatchId = 1,
                            BankFormatId = 1
                        },
                        new
                        {
                            BatchId = 2,
                            BankFormatId = 2
                        },
                        new
                        {
                            BatchId = 3,
                            BankFormatId = 3
                        },
                        new
                        {
                            BatchId = 4,
                            BankFormatId = 4
                        });
                });

            modelBuilder.Entity("Domain.Entities.UserAddress", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UserDataNavCardNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("AddressId");

                    b.HasIndex("UserDataNavCardNumber");

                    b.ToTable("UserAddress");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            Address = "Av. Mitre 3353",
                            City = "Florencio Varela",
                            State = "Mendoza",
                            ZipCode = 2078
                        },
                        new
                        {
                            AddressId = 2,
                            Address = "Juan Domingo Peron 4296",
                            City = "Resistencia",
                            State = "Santa Fe",
                            ZipCode = 2692
                        },
                        new
                        {
                            AddressId = 3,
                            Address = "Av. Cabildo 5825",
                            City = "Mina Clavero",
                            State = "Tucumán",
                            ZipCode = 2813
                        },
                        new
                        {
                            AddressId = 4,
                            Address = "Av. Manuel Belgrano 2808",
                            City = "Mina Clavero",
                            State = "Salta",
                            ZipCode = 6851
                        },
                        new
                        {
                            AddressId = 5,
                            Address = "Las Heras 6734",
                            City = "Mina Clavero",
                            State = "Santa Fe",
                            ZipCode = 6886
                        },
                        new
                        {
                            AddressId = 6,
                            Address = "Castro Barro 8461",
                            City = "Las Leñas",
                            State = "Buenos Aires",
                            ZipCode = 4578
                        },
                        new
                        {
                            AddressId = 7,
                            Address = "Castro Barro 7940",
                            City = "Mina Clavero",
                            State = "Tucumán",
                            ZipCode = 9054
                        },
                        new
                        {
                            AddressId = 8,
                            Address = "Av. Independencia 4664",
                            City = "Palermo",
                            State = "Chaco",
                            ZipCode = 8359
                        },
                        new
                        {
                            AddressId = 9,
                            Address = "Av. Manuel Belgrano 2519",
                            City = "Florencio Varela",
                            State = "Córdoba",
                            ZipCode = 9211
                        },
                        new
                        {
                            AddressId = 10,
                            Address = "Hiprito Yrigiyen 2855",
                            City = "Mina Clavero",
                            State = "Santa Fe",
                            ZipCode = 9295
                        },
                        new
                        {
                            AddressId = 11,
                            Address = "Castro Barro 3421",
                            City = "Florencio Varela",
                            State = "Entre Ríos",
                            ZipCode = 2921
                        },
                        new
                        {
                            AddressId = 12,
                            Address = "Av. Manuel Belgrano 1773",
                            City = "Resistencia",
                            State = "Tucumán",
                            ZipCode = 5954
                        },
                        new
                        {
                            AddressId = 13,
                            Address = "Hiprito Yrigiyen 6764",
                            City = "Mina Clavero",
                            State = "Santa Fe",
                            ZipCode = 8350
                        },
                        new
                        {
                            AddressId = 14,
                            Address = "Francisco Pienovi 1866",
                            City = "La Boca",
                            State = "Mendoza",
                            ZipCode = 3812
                        },
                        new
                        {
                            AddressId = 15,
                            Address = "Av. Mitre 7100",
                            City = "Mina Clavero",
                            State = "Mendoza",
                            ZipCode = 3309
                        },
                        new
                        {
                            AddressId = 16,
                            Address = "Francisco Pienovi 4327",
                            City = "La Boca",
                            State = "Buenos Aires",
                            ZipCode = 2492
                        },
                        new
                        {
                            AddressId = 17,
                            Address = "Av. Independencia 5615",
                            City = "La Boca",
                            State = "Buenos Aires",
                            ZipCode = 3478
                        },
                        new
                        {
                            AddressId = 18,
                            Address = "Hiprito Yrigiyen 6879",
                            City = "San Lorenzo",
                            State = "Buenos Aires",
                            ZipCode = 3936
                        },
                        new
                        {
                            AddressId = 19,
                            Address = "Cochabamba 1647",
                            City = "Yerba Buena",
                            State = "Córdoba",
                            ZipCode = 6852
                        },
                        new
                        {
                            AddressId = 20,
                            Address = "Francisco Pienovi 5272",
                            City = "Palermo",
                            State = "Corrientes",
                            ZipCode = 7190
                        },
                        new
                        {
                            AddressId = 21,
                            Address = "Hiprito Yrigiyen 5561",
                            City = "Florencio Varela",
                            State = "Córdoba",
                            ZipCode = 6399
                        },
                        new
                        {
                            AddressId = 22,
                            Address = "Juan Domingo Peron 4486",
                            City = "Bariloche",
                            State = "Corrientes",
                            ZipCode = 4083
                        },
                        new
                        {
                            AddressId = 23,
                            Address = "Castro Barro 1963",
                            City = "Mina Clavero",
                            State = "Mendoza",
                            ZipCode = 8956
                        },
                        new
                        {
                            AddressId = 24,
                            Address = "Francisco Pienovi 9453",
                            City = "Resistencia",
                            State = "Buenos Aires",
                            ZipCode = 1398
                        },
                        new
                        {
                            AddressId = 25,
                            Address = "Av. San Martin 6484",
                            City = "La Boca",
                            State = "Misiones",
                            ZipCode = 9274
                        },
                        new
                        {
                            AddressId = 26,
                            Address = "Hiprito Yrigiyen 9569",
                            City = "Las Leñas",
                            State = "Misiones",
                            ZipCode = 2163
                        },
                        new
                        {
                            AddressId = 27,
                            Address = "Av. Los Quilmes 4193",
                            City = "Resistencia",
                            State = "Tucumán",
                            ZipCode = 4045
                        },
                        new
                        {
                            AddressId = 28,
                            Address = "Av. Independencia 2401",
                            City = "Palermo",
                            State = "Tucumán",
                            ZipCode = 2219
                        },
                        new
                        {
                            AddressId = 29,
                            Address = "Cochabamba 7015",
                            City = "San Lorenzo",
                            State = "Córdoba",
                            ZipCode = 5951
                        },
                        new
                        {
                            AddressId = 30,
                            Address = "Av. San Martin 7762",
                            City = "Resistencia",
                            State = "Salta",
                            ZipCode = 7467
                        },
                        new
                        {
                            AddressId = 31,
                            Address = "Cochabamba 9773",
                            City = "Las Leñas",
                            State = "Tucumán",
                            ZipCode = 7679
                        },
                        new
                        {
                            AddressId = 32,
                            Address = "Cochabamba 4169",
                            City = "Mina Clavero",
                            State = "Santa Fe",
                            ZipCode = 4945
                        },
                        new
                        {
                            AddressId = 33,
                            Address = "Av. Los Quilmes 2966",
                            City = "Bariloche",
                            State = "Corrientes",
                            ZipCode = 1894
                        },
                        new
                        {
                            AddressId = 34,
                            Address = "Castro Barro 5294",
                            City = "Resistencia",
                            State = "Tucumán",
                            ZipCode = 2353
                        },
                        new
                        {
                            AddressId = 35,
                            Address = "Av. Cabildo 7090",
                            City = "Ushuaia",
                            State = "Corrientes",
                            ZipCode = 7312
                        },
                        new
                        {
                            AddressId = 36,
                            Address = "Av. Cabildo 6041",
                            City = "Mina Clavero",
                            State = "Entre Ríos",
                            ZipCode = 7618
                        },
                        new
                        {
                            AddressId = 37,
                            Address = "Las Heras 8140",
                            City = "Mina Clavero",
                            State = "Misiones",
                            ZipCode = 9705
                        },
                        new
                        {
                            AddressId = 38,
                            Address = "Conesa 2102",
                            City = "Florencio Varela",
                            State = "Santa Fe",
                            ZipCode = 6373
                        },
                        new
                        {
                            AddressId = 39,
                            Address = "Av. Manuel Belgrano 2297",
                            City = "Palermo",
                            State = "Corrientes",
                            ZipCode = 1819
                        },
                        new
                        {
                            AddressId = 40,
                            Address = "Av. Los Quilmes 5876",
                            City = "Bariloche",
                            State = "Misiones",
                            ZipCode = 9632
                        },
                        new
                        {
                            AddressId = 41,
                            Address = "Hiprito Yrigiyen 4108",
                            City = "La Boca",
                            State = "Entre Ríos",
                            ZipCode = 3220
                        },
                        new
                        {
                            AddressId = 42,
                            Address = "Av. Cabildo 4432",
                            City = "Palermo",
                            State = "Entre Ríos",
                            ZipCode = 8386
                        },
                        new
                        {
                            AddressId = 43,
                            Address = "Castro Barro 3710",
                            City = "Ushuaia",
                            State = "Corrientes",
                            ZipCode = 9785
                        },
                        new
                        {
                            AddressId = 44,
                            Address = "Castro Barro 9962",
                            City = "Palermo",
                            State = "Corrientes",
                            ZipCode = 7983
                        },
                        new
                        {
                            AddressId = 45,
                            Address = "Av. Independencia 1358",
                            City = "Palermo",
                            State = "Córdoba",
                            ZipCode = 5525
                        },
                        new
                        {
                            AddressId = 46,
                            Address = "Cochabamba 8342",
                            City = "Palermo",
                            State = "Corrientes",
                            ZipCode = 5719
                        },
                        new
                        {
                            AddressId = 47,
                            Address = "Cochabamba 5857",
                            City = "Ushuaia",
                            State = "Tucumán",
                            ZipCode = 2588
                        },
                        new
                        {
                            AddressId = 48,
                            Address = "Conesa 4535",
                            City = "Las Leñas",
                            State = "Entre Ríos",
                            ZipCode = 9531
                        },
                        new
                        {
                            AddressId = 49,
                            Address = "Cochabamba 3991",
                            City = "Ushuaia",
                            State = "Mendoza",
                            ZipCode = 2801
                        },
                        new
                        {
                            AddressId = 50,
                            Address = "Las Heras 6515",
                            City = "La Boca",
                            State = "Santa Fe",
                            ZipCode = 7202
                        },
                        new
                        {
                            AddressId = 51,
                            Address = "Francisco Pienovi 3236",
                            City = "Las Leñas",
                            State = "Corrientes",
                            ZipCode = 2023
                        },
                        new
                        {
                            AddressId = 52,
                            Address = "Av. San Martin 5251",
                            City = "Mina Clavero",
                            State = "Córdoba",
                            ZipCode = 8068
                        },
                        new
                        {
                            AddressId = 53,
                            Address = "Av. Independencia 4567",
                            City = "San Lorenzo",
                            State = "Corrientes",
                            ZipCode = 7665
                        },
                        new
                        {
                            AddressId = 54,
                            Address = "Francisco Pienovi 7358",
                            City = "Ushuaia",
                            State = "Chaco",
                            ZipCode = 1533
                        },
                        new
                        {
                            AddressId = 55,
                            Address = "Av. San Martin 5949",
                            City = "Ushuaia",
                            State = "Corrientes",
                            ZipCode = 5373
                        },
                        new
                        {
                            AddressId = 56,
                            Address = "Av. Independencia 8879",
                            City = "Mina Clavero",
                            State = "Chaco",
                            ZipCode = 8297
                        },
                        new
                        {
                            AddressId = 57,
                            Address = "Av. Cabildo 7454",
                            City = "Ushuaia",
                            State = "Misiones",
                            ZipCode = 1695
                        },
                        new
                        {
                            AddressId = 58,
                            Address = "Castro Barro 9310",
                            City = "Ushuaia",
                            State = "Misiones",
                            ZipCode = 9848
                        },
                        new
                        {
                            AddressId = 59,
                            Address = "Las Heras 3866",
                            City = "La Boca",
                            State = "Salta",
                            ZipCode = 8611
                        },
                        new
                        {
                            AddressId = 60,
                            Address = "Castro Barro 1568",
                            City = "Mina Clavero",
                            State = "Salta",
                            ZipCode = 3870
                        },
                        new
                        {
                            AddressId = 61,
                            Address = "Juan Domingo Peron 4946",
                            City = "Yerba Buena",
                            State = "Córdoba",
                            ZipCode = 3673
                        },
                        new
                        {
                            AddressId = 62,
                            Address = "Conesa 2756",
                            City = "Ushuaia",
                            State = "Tucumán",
                            ZipCode = 9865
                        },
                        new
                        {
                            AddressId = 63,
                            Address = "Av. Mitre 5637",
                            City = "Florencio Varela",
                            State = "Corrientes",
                            ZipCode = 2976
                        },
                        new
                        {
                            AddressId = 64,
                            Address = "Castro Barro 7499",
                            City = "Ushuaia",
                            State = "Misiones",
                            ZipCode = 5798
                        },
                        new
                        {
                            AddressId = 65,
                            Address = "Cochabamba 5145",
                            City = "Resistencia",
                            State = "Buenos Aires",
                            ZipCode = 1945
                        },
                        new
                        {
                            AddressId = 66,
                            Address = "Av. San Martin 6688",
                            City = "Mina Clavero",
                            State = "Buenos Aires",
                            ZipCode = 9428
                        },
                        new
                        {
                            AddressId = 67,
                            Address = "Juan Domingo Peron 5997",
                            City = "Mina Clavero",
                            State = "Chaco",
                            ZipCode = 3252
                        },
                        new
                        {
                            AddressId = 68,
                            Address = "Av. San Martin 3777",
                            City = "San Lorenzo",
                            State = "Salta",
                            ZipCode = 8691
                        },
                        new
                        {
                            AddressId = 69,
                            Address = "Av. Cabildo 4080",
                            City = "La Boca",
                            State = "Buenos Aires",
                            ZipCode = 7690
                        },
                        new
                        {
                            AddressId = 70,
                            Address = "Luis Braile 4864",
                            City = "Bariloche",
                            State = "Córdoba",
                            ZipCode = 2032
                        },
                        new
                        {
                            AddressId = 71,
                            Address = "Cochabamba 2043",
                            City = "Las Leñas",
                            State = "Entre Ríos",
                            ZipCode = 9671
                        },
                        new
                        {
                            AddressId = 72,
                            Address = "Luis Braile 4728",
                            City = "Resistencia",
                            State = "Chaco",
                            ZipCode = 6281
                        },
                        new
                        {
                            AddressId = 73,
                            Address = "Francisco Pienovi 8293",
                            City = "Resistencia",
                            State = "Mendoza",
                            ZipCode = 2628
                        },
                        new
                        {
                            AddressId = 74,
                            Address = "Av. Mitre 2762",
                            City = "Yerba Buena",
                            State = "Santa Fe",
                            ZipCode = 3028
                        },
                        new
                        {
                            AddressId = 75,
                            Address = "Av. San Martin 1224",
                            City = "Yerba Buena",
                            State = "Santa Fe",
                            ZipCode = 9405
                        },
                        new
                        {
                            AddressId = 76,
                            Address = "Cochabamba 9369",
                            City = "La Boca",
                            State = "Entre Ríos",
                            ZipCode = 4035
                        },
                        new
                        {
                            AddressId = 77,
                            Address = "Luis Braile 2516",
                            City = "Las Leñas",
                            State = "Corrientes",
                            ZipCode = 2227
                        },
                        new
                        {
                            AddressId = 78,
                            Address = "Av. Cabildo 2229",
                            City = "Florencio Varela",
                            State = "Chaco",
                            ZipCode = 8997
                        },
                        new
                        {
                            AddressId = 79,
                            Address = "Las Heras 9528",
                            City = "San Lorenzo",
                            State = "Mendoza",
                            ZipCode = 8891
                        },
                        new
                        {
                            AddressId = 80,
                            Address = "Av. Mitre 3365",
                            City = "La Boca",
                            State = "Santa Fe",
                            ZipCode = 6500
                        });
                });

            modelBuilder.Entity("Domain.Entities.UserData", b =>
                {
                    b.Property<long>("CardNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CardNumber"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("BatchCardId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardNumber");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("BatchCardId");

                    b.ToTable("UserData");

                    b.HasData(
                        new
                        {
                            CardNumber = 934895327027L,
                            AddressId = 1,
                            BatchCardId = 1,
                            Name = "Carlos",
                            Surname = "Martinez"
                        },
                        new
                        {
                            CardNumber = 517205147808L,
                            AddressId = 2,
                            BatchCardId = 1,
                            Name = "Laura",
                            Surname = "Sanchez"
                        },
                        new
                        {
                            CardNumber = 858235777653L,
                            AddressId = 3,
                            BatchCardId = 1,
                            Name = "Pedro",
                            Surname = "Fernandez"
                        },
                        new
                        {
                            CardNumber = 949148462237L,
                            AddressId = 4,
                            BatchCardId = 1,
                            Name = "Lucas",
                            Surname = "Garcia"
                        },
                        new
                        {
                            CardNumber = 531576477471L,
                            AddressId = 5,
                            BatchCardId = 1,
                            Name = "Valentina",
                            Surname = "Martinez"
                        },
                        new
                        {
                            CardNumber = 443718292223L,
                            AddressId = 6,
                            BatchCardId = 1,
                            Name = "Sofia",
                            Surname = "Torres"
                        },
                        new
                        {
                            CardNumber = 550500446342L,
                            AddressId = 7,
                            BatchCardId = 1,
                            Name = "Ana",
                            Surname = "Martinez"
                        },
                        new
                        {
                            CardNumber = 877566093970L,
                            AddressId = 8,
                            BatchCardId = 1,
                            Name = "Lucas",
                            Surname = "Fernandez"
                        },
                        new
                        {
                            CardNumber = 675001445824L,
                            AddressId = 9,
                            BatchCardId = 1,
                            Name = "Maria",
                            Surname = "Sanchez"
                        },
                        new
                        {
                            CardNumber = 616570514581L,
                            AddressId = 10,
                            BatchCardId = 1,
                            Name = "Pedro",
                            Surname = "Fernandez"
                        },
                        new
                        {
                            CardNumber = 943177695623L,
                            AddressId = 11,
                            BatchCardId = 1,
                            Name = "Ana",
                            Surname = "Torres"
                        },
                        new
                        {
                            CardNumber = 409859330226L,
                            AddressId = 12,
                            BatchCardId = 1,
                            Name = "Carlos",
                            Surname = "Garcia"
                        },
                        new
                        {
                            CardNumber = 193883332984L,
                            AddressId = 13,
                            BatchCardId = 1,
                            Name = "Pedro",
                            Surname = "Torres"
                        },
                        new
                        {
                            CardNumber = 442479958502L,
                            AddressId = 14,
                            BatchCardId = 1,
                            Name = "Ana",
                            Surname = "Sanchez"
                        },
                        new
                        {
                            CardNumber = 652638819004L,
                            AddressId = 15,
                            BatchCardId = 1,
                            Name = "Valentina",
                            Surname = "Gonzalez"
                        },
                        new
                        {
                            CardNumber = 731014440275L,
                            AddressId = 16,
                            BatchCardId = 1,
                            Name = "Carlos",
                            Surname = "Gonzalez"
                        },
                        new
                        {
                            CardNumber = 564322736034L,
                            AddressId = 17,
                            BatchCardId = 1,
                            Name = "Diego",
                            Surname = "Lopez"
                        },
                        new
                        {
                            CardNumber = 819811724854L,
                            AddressId = 18,
                            BatchCardId = 1,
                            Name = "Lucas",
                            Surname = "Lopez"
                        },
                        new
                        {
                            CardNumber = 493871641950L,
                            AddressId = 19,
                            BatchCardId = 1,
                            Name = "Diego",
                            Surname = "Garcia"
                        },
                        new
                        {
                            CardNumber = 313635702648L,
                            AddressId = 20,
                            BatchCardId = 1,
                            Name = "Pedro",
                            Surname = "Fernandez"
                        },
                        new
                        {
                            CardNumber = 636654232459L,
                            AddressId = 21,
                            BatchCardId = 2,
                            Name = "Maria",
                            Surname = "Fernandez"
                        },
                        new
                        {
                            CardNumber = 349885525325L,
                            AddressId = 22,
                            BatchCardId = 2,
                            Name = "Juan",
                            Surname = "Martinez"
                        },
                        new
                        {
                            CardNumber = 279591263186L,
                            AddressId = 23,
                            BatchCardId = 2,
                            Name = "Juan",
                            Surname = "Garcia"
                        },
                        new
                        {
                            CardNumber = 931569297702L,
                            AddressId = 24,
                            BatchCardId = 2,
                            Name = "Sofia",
                            Surname = "Garcia"
                        },
                        new
                        {
                            CardNumber = 282522194456L,
                            AddressId = 25,
                            BatchCardId = 2,
                            Name = "Lucas",
                            Surname = "Rodriguez"
                        },
                        new
                        {
                            CardNumber = 199124245002L,
                            AddressId = 26,
                            BatchCardId = 2,
                            Name = "Maria",
                            Surname = "Gonzalez"
                        },
                        new
                        {
                            CardNumber = 683205162115L,
                            AddressId = 27,
                            BatchCardId = 2,
                            Name = "Juan",
                            Surname = "Martinez"
                        },
                        new
                        {
                            CardNumber = 301542354826L,
                            AddressId = 28,
                            BatchCardId = 2,
                            Name = "Juan",
                            Surname = "Garcia"
                        },
                        new
                        {
                            CardNumber = 286749475866L,
                            AddressId = 29,
                            BatchCardId = 2,
                            Name = "Pedro",
                            Surname = "Ramirez"
                        },
                        new
                        {
                            CardNumber = 688675823237L,
                            AddressId = 30,
                            BatchCardId = 2,
                            Name = "Ana",
                            Surname = "Gonzalez"
                        },
                        new
                        {
                            CardNumber = 705636930462L,
                            AddressId = 31,
                            BatchCardId = 2,
                            Name = "Maria",
                            Surname = "Garcia"
                        },
                        new
                        {
                            CardNumber = 104984426202L,
                            AddressId = 32,
                            BatchCardId = 2,
                            Name = "Ana",
                            Surname = "Martinez"
                        },
                        new
                        {
                            CardNumber = 809064001913L,
                            AddressId = 33,
                            BatchCardId = 2,
                            Name = "Lucas",
                            Surname = "Rodriguez"
                        },
                        new
                        {
                            CardNumber = 839389623709L,
                            AddressId = 34,
                            BatchCardId = 2,
                            Name = "Juan",
                            Surname = "Fernandez"
                        },
                        new
                        {
                            CardNumber = 536718815238L,
                            AddressId = 35,
                            BatchCardId = 2,
                            Name = "Laura",
                            Surname = "Garcia"
                        },
                        new
                        {
                            CardNumber = 876869204860L,
                            AddressId = 36,
                            BatchCardId = 2,
                            Name = "Valentina",
                            Surname = "Torres"
                        },
                        new
                        {
                            CardNumber = 771854759318L,
                            AddressId = 37,
                            BatchCardId = 2,
                            Name = "Carlos",
                            Surname = "Rodriguez"
                        },
                        new
                        {
                            CardNumber = 912319400672L,
                            AddressId = 38,
                            BatchCardId = 2,
                            Name = "Pedro",
                            Surname = "Garcia"
                        },
                        new
                        {
                            CardNumber = 348784017020L,
                            AddressId = 39,
                            BatchCardId = 2,
                            Name = "Maria",
                            Surname = "Fernandez"
                        },
                        new
                        {
                            CardNumber = 928086033866L,
                            AddressId = 40,
                            BatchCardId = 2,
                            Name = "Carlos",
                            Surname = "Torres"
                        },
                        new
                        {
                            CardNumber = 905339950220L,
                            AddressId = 41,
                            BatchCardId = 3,
                            Name = "Sofia",
                            Surname = "Rodriguez"
                        },
                        new
                        {
                            CardNumber = 611567584252L,
                            AddressId = 42,
                            BatchCardId = 3,
                            Name = "Valentina",
                            Surname = "Fernandez"
                        },
                        new
                        {
                            CardNumber = 127255809457L,
                            AddressId = 43,
                            BatchCardId = 3,
                            Name = "Pedro",
                            Surname = "Lopez"
                        },
                        new
                        {
                            CardNumber = 877390474439L,
                            AddressId = 44,
                            BatchCardId = 3,
                            Name = "Maria",
                            Surname = "Ramirez"
                        },
                        new
                        {
                            CardNumber = 778621705212L,
                            AddressId = 45,
                            BatchCardId = 3,
                            Name = "Maria",
                            Surname = "Martinez"
                        },
                        new
                        {
                            CardNumber = 875049562843L,
                            AddressId = 46,
                            BatchCardId = 3,
                            Name = "Juan",
                            Surname = "Perez"
                        },
                        new
                        {
                            CardNumber = 268092387411L,
                            AddressId = 47,
                            BatchCardId = 3,
                            Name = "Maria",
                            Surname = "Lopez"
                        },
                        new
                        {
                            CardNumber = 502092218442L,
                            AddressId = 48,
                            BatchCardId = 3,
                            Name = "Ana",
                            Surname = "Garcia"
                        },
                        new
                        {
                            CardNumber = 668859626535L,
                            AddressId = 49,
                            BatchCardId = 3,
                            Name = "Maria",
                            Surname = "Gonzalez"
                        },
                        new
                        {
                            CardNumber = 120150195521L,
                            AddressId = 50,
                            BatchCardId = 3,
                            Name = "Diego",
                            Surname = "Gonzalez"
                        },
                        new
                        {
                            CardNumber = 651441385659L,
                            AddressId = 51,
                            BatchCardId = 3,
                            Name = "Valentina",
                            Surname = "Sanchez"
                        },
                        new
                        {
                            CardNumber = 679722828409L,
                            AddressId = 52,
                            BatchCardId = 3,
                            Name = "Carlos",
                            Surname = "Perez"
                        },
                        new
                        {
                            CardNumber = 887120098749L,
                            AddressId = 53,
                            BatchCardId = 3,
                            Name = "Diego",
                            Surname = "Ramirez"
                        },
                        new
                        {
                            CardNumber = 468914735552L,
                            AddressId = 54,
                            BatchCardId = 3,
                            Name = "Ana",
                            Surname = "Martinez"
                        },
                        new
                        {
                            CardNumber = 462737530792L,
                            AddressId = 55,
                            BatchCardId = 3,
                            Name = "Diego",
                            Surname = "Gonzalez"
                        },
                        new
                        {
                            CardNumber = 788968014035L,
                            AddressId = 56,
                            BatchCardId = 3,
                            Name = "Valentina",
                            Surname = "Lopez"
                        },
                        new
                        {
                            CardNumber = 797921530473L,
                            AddressId = 57,
                            BatchCardId = 3,
                            Name = "Ana",
                            Surname = "Martinez"
                        },
                        new
                        {
                            CardNumber = 832437564222L,
                            AddressId = 58,
                            BatchCardId = 3,
                            Name = "Pedro",
                            Surname = "Gonzalez"
                        },
                        new
                        {
                            CardNumber = 389605205122L,
                            AddressId = 59,
                            BatchCardId = 3,
                            Name = "Juan",
                            Surname = "Garcia"
                        },
                        new
                        {
                            CardNumber = 188503348571L,
                            AddressId = 60,
                            BatchCardId = 3,
                            Name = "Ana",
                            Surname = "Martinez"
                        },
                        new
                        {
                            CardNumber = 657923585670L,
                            AddressId = 61,
                            BatchCardId = 4,
                            Name = "Pedro",
                            Surname = "Fernandez"
                        },
                        new
                        {
                            CardNumber = 127551128546L,
                            AddressId = 62,
                            BatchCardId = 4,
                            Name = "Laura",
                            Surname = "Torres"
                        },
                        new
                        {
                            CardNumber = 589746474757L,
                            AddressId = 63,
                            BatchCardId = 4,
                            Name = "Valentina",
                            Surname = "Fernandez"
                        },
                        new
                        {
                            CardNumber = 786349225145L,
                            AddressId = 64,
                            BatchCardId = 4,
                            Name = "Juan",
                            Surname = "Torres"
                        },
                        new
                        {
                            CardNumber = 126808894654L,
                            AddressId = 65,
                            BatchCardId = 4,
                            Name = "Lucas",
                            Surname = "Perez"
                        },
                        new
                        {
                            CardNumber = 421050220299L,
                            AddressId = 66,
                            BatchCardId = 4,
                            Name = "Carlos",
                            Surname = "Torres"
                        },
                        new
                        {
                            CardNumber = 361971591231L,
                            AddressId = 67,
                            BatchCardId = 4,
                            Name = "Carlos",
                            Surname = "Perez"
                        },
                        new
                        {
                            CardNumber = 191910677970L,
                            AddressId = 68,
                            BatchCardId = 4,
                            Name = "Laura",
                            Surname = "Sanchez"
                        },
                        new
                        {
                            CardNumber = 818388420172L,
                            AddressId = 69,
                            BatchCardId = 4,
                            Name = "Carlos",
                            Surname = "Gonzalez"
                        },
                        new
                        {
                            CardNumber = 369450969051L,
                            AddressId = 70,
                            BatchCardId = 4,
                            Name = "Pedro",
                            Surname = "Fernandez"
                        },
                        new
                        {
                            CardNumber = 924106156753L,
                            AddressId = 71,
                            BatchCardId = 4,
                            Name = "Sofia",
                            Surname = "Lopez"
                        },
                        new
                        {
                            CardNumber = 711774331733L,
                            AddressId = 72,
                            BatchCardId = 4,
                            Name = "Pedro",
                            Surname = "Lopez"
                        },
                        new
                        {
                            CardNumber = 245230110400L,
                            AddressId = 73,
                            BatchCardId = 4,
                            Name = "Valentina",
                            Surname = "Rodriguez"
                        },
                        new
                        {
                            CardNumber = 997180090013L,
                            AddressId = 74,
                            BatchCardId = 4,
                            Name = "Maria",
                            Surname = "Garcia"
                        },
                        new
                        {
                            CardNumber = 530030203331L,
                            AddressId = 75,
                            BatchCardId = 4,
                            Name = "Valentina",
                            Surname = "Gonzalez"
                        },
                        new
                        {
                            CardNumber = 666309240975L,
                            AddressId = 76,
                            BatchCardId = 4,
                            Name = "Laura",
                            Surname = "Perez"
                        },
                        new
                        {
                            CardNumber = 363298115423L,
                            AddressId = 77,
                            BatchCardId = 4,
                            Name = "Juan",
                            Surname = "Lopez"
                        },
                        new
                        {
                            CardNumber = 576620660545L,
                            AddressId = 78,
                            BatchCardId = 4,
                            Name = "Laura",
                            Surname = "Martinez"
                        },
                        new
                        {
                            CardNumber = 717983071532L,
                            AddressId = 79,
                            BatchCardId = 4,
                            Name = "Ana",
                            Surname = "Rodriguez"
                        },
                        new
                        {
                            CardNumber = 224025074390L,
                            AddressId = 80,
                            BatchCardId = 4,
                            Name = "Sofia",
                            Surname = "Perez"
                        });
                });

            modelBuilder.Entity("Domain.Entities.BatchCard", b =>
                {
                    b.HasOne("Domain.Entities.BankFormat", "BankFormatNav")
                        .WithMany("BatchCardCollector")
                        .HasForeignKey("BankFormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankFormatNav");
                });

            modelBuilder.Entity("Domain.Entities.UserAddress", b =>
                {
                    b.HasOne("Domain.Entities.UserData", "UserDataNav")
                        .WithMany()
                        .HasForeignKey("UserDataNavCardNumber");

                    b.Navigation("UserDataNav");
                });

            modelBuilder.Entity("Domain.Entities.UserData", b =>
                {
                    b.HasOne("Domain.Entities.UserAddress", "AddressNav")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.UserData", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.BatchCard", "BatchCardNav")
                        .WithMany("UserDataCollection")
                        .HasForeignKey("BatchCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddressNav");

                    b.Navigation("BatchCardNav");
                });

            modelBuilder.Entity("Domain.Entities.BankFormat", b =>
                {
                    b.Navigation("BatchCardCollector");
                });

            modelBuilder.Entity("Domain.Entities.BatchCard", b =>
                {
                    b.Navigation("UserDataCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
