// <auto-generated />
using Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.BankFormat", b =>
                {
                    b.Property<int>("BankFormatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankFormatId"));

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slogan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BankFormatId");

                    b.ToTable("BankFormat");

                    b.HasData(
                        new
                        {
                            BankFormatId = 1,
                            Logo = "https://i.pinimg.com/originals/5a/55/9d/5a559d02bc8996d233ba05d8fb2d56e3.png",
                            Name = "BBVA Frances",
                            Slogan = "Creando Oportunidades"
                        },
                        new
                        {
                            BankFormatId = 2,
                            Logo = "https://iconape.com/wp-content/files/ko/182549/png/182549.png",
                            Name = "Grupo Galicia",
                            Slogan = "Te merecés lo mejor, hacete Galicia"
                        },
                        new
                        {
                            BankFormatId = 3,
                            Logo = "https://companieslogo.com/img/orig/BMA-99c2b89d.png?t=1684228585",
                            Name = "Banco Macro",
                            Slogan = "Pensá en grande. Pensá en Macro"
                        },
                        new
                        {
                            BankFormatId = 4,
                            Logo = "https://1000marcas.net/wp-content/uploads/2020/07/Logo-ICBC.png",
                            Name = "ICBC",
                            Slogan = "ICBC, si ;)"
                        });
                });

            modelBuilder.Entity("Domain.Entities.BatchCard", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchId"));

                    b.Property<int>("BankFormatId")
                        .HasColumnType("int");

                    b.HasKey("BatchId");

                    b.HasIndex("BankFormatId");

                    b.ToTable("BatchCard");

                    b.HasData(
                        new
                        {
                            BatchId = 1,
                            BankFormatId = 1
                        },
                        new
                        {
                            BatchId = 2,
                            BankFormatId = 2
                        },
                        new
                        {
                            BatchId = 3,
                            BankFormatId = 3
                        },
                        new
                        {
                            BatchId = 4,
                            BankFormatId = 4
                        });
                });

            modelBuilder.Entity("Domain.Entities.UserAddress", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("AddressId");

                    b.ToTable("UserAddress");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            Address = "Hiprito Yrigiyen 9792",
                            City = "Mina Clavero",
                            State = "Tucumán",
                            ZipCode = 3621
                        },
                        new
                        {
                            AddressId = 2,
                            Address = "Av. San Martin 3492",
                            City = "Resistencia",
                            State = "Santa Fe",
                            ZipCode = 1454
                        },
                        new
                        {
                            AddressId = 3,
                            Address = "Av. Cabildo 1982",
                            City = "Mina Clavero",
                            State = "Santa Fe",
                            ZipCode = 1913
                        },
                        new
                        {
                            AddressId = 4,
                            Address = "Av. Los Quilmes 4148",
                            City = "Yerba Buena",
                            State = "Buenos Aires",
                            ZipCode = 5249
                        },
                        new
                        {
                            AddressId = 5,
                            Address = "Las Heras 9764",
                            City = "Mina Clavero",
                            State = "Chaco",
                            ZipCode = 5678
                        },
                        new
                        {
                            AddressId = 6,
                            Address = "Av. Cabildo 4712",
                            City = "San Lorenzo",
                            State = "Chaco",
                            ZipCode = 5826
                        },
                        new
                        {
                            AddressId = 7,
                            Address = "Av. Mitre 1164",
                            City = "Ushuaia",
                            State = "Santa Fe",
                            ZipCode = 7972
                        },
                        new
                        {
                            AddressId = 8,
                            Address = "Luis Braile 4615",
                            City = "Palermo",
                            State = "Santa Fe",
                            ZipCode = 1316
                        },
                        new
                        {
                            AddressId = 9,
                            Address = "Av. Los Quilmes 1828",
                            City = "Las Leñas",
                            State = "Córdoba",
                            ZipCode = 2333
                        },
                        new
                        {
                            AddressId = 10,
                            Address = "Av. Cabildo 5998",
                            City = "San Lorenzo",
                            State = "Córdoba",
                            ZipCode = 9042
                        },
                        new
                        {
                            AddressId = 11,
                            Address = "Francisco Pienovi 8371",
                            City = "San Lorenzo",
                            State = "Entre Ríos",
                            ZipCode = 2543
                        },
                        new
                        {
                            AddressId = 12,
                            Address = "Conesa 6276",
                            City = "Ushuaia",
                            State = "Mendoza",
                            ZipCode = 7630
                        },
                        new
                        {
                            AddressId = 13,
                            Address = "Conesa 4954",
                            City = "Florencio Varela",
                            State = "Santa Fe",
                            ZipCode = 3464
                        },
                        new
                        {
                            AddressId = 14,
                            Address = "Av. Independencia 4432",
                            City = "Mina Clavero",
                            State = "Salta",
                            ZipCode = 4232
                        },
                        new
                        {
                            AddressId = 15,
                            Address = "Cochabamba 6108",
                            City = "Mina Clavero",
                            State = "Chaco",
                            ZipCode = 3408
                        },
                        new
                        {
                            AddressId = 16,
                            Address = "Conesa 3946",
                            City = "San Lorenzo",
                            State = "Misiones",
                            ZipCode = 3587
                        },
                        new
                        {
                            AddressId = 17,
                            Address = "Av. Los Quilmes 5159",
                            City = "San Lorenzo",
                            State = "Salta",
                            ZipCode = 2254
                        },
                        new
                        {
                            AddressId = 18,
                            Address = "Francisco Pienovi 6202",
                            City = "Florencio Varela",
                            State = "Santa Fe",
                            ZipCode = 2317
                        },
                        new
                        {
                            AddressId = 19,
                            Address = "Av. Cabildo 7092",
                            City = "Palermo",
                            State = "Córdoba",
                            ZipCode = 7558
                        },
                        new
                        {
                            AddressId = 20,
                            Address = "Las Heras 2895",
                            City = "Yerba Buena",
                            State = "Misiones",
                            ZipCode = 1657
                        },
                        new
                        {
                            AddressId = 21,
                            Address = "Las Heras 3569",
                            City = "Bariloche",
                            State = "Buenos Aires",
                            ZipCode = 7118
                        },
                        new
                        {
                            AddressId = 22,
                            Address = "Av. Cabildo 4125",
                            City = "Yerba Buena",
                            State = "Santa Fe",
                            ZipCode = 8761
                        },
                        new
                        {
                            AddressId = 23,
                            Address = "Av. Los Quilmes 8701",
                            City = "Ushuaia",
                            State = "Misiones",
                            ZipCode = 4728
                        },
                        new
                        {
                            AddressId = 24,
                            Address = "Cochabamba 7544",
                            City = "Florencio Varela",
                            State = "Buenos Aires",
                            ZipCode = 4940
                        },
                        new
                        {
                            AddressId = 25,
                            Address = "Francisco Pienovi 9300",
                            City = "Ushuaia",
                            State = "Entre Ríos",
                            ZipCode = 4175
                        },
                        new
                        {
                            AddressId = 26,
                            Address = "Av. Manuel Belgrano 1460",
                            City = "Palermo",
                            State = "Santa Fe",
                            ZipCode = 7571
                        },
                        new
                        {
                            AddressId = 27,
                            Address = "Av. Mitre 2857",
                            City = "Mina Clavero",
                            State = "Chaco",
                            ZipCode = 2401
                        },
                        new
                        {
                            AddressId = 28,
                            Address = "Av. Cabildo 2589",
                            City = "Mina Clavero",
                            State = "Misiones",
                            ZipCode = 1476
                        },
                        new
                        {
                            AddressId = 29,
                            Address = "Hiprito Yrigiyen 6873",
                            City = "Ushuaia",
                            State = "Salta",
                            ZipCode = 6114
                        },
                        new
                        {
                            AddressId = 30,
                            Address = "Av. Los Quilmes 5050",
                            City = "Bariloche",
                            State = "Córdoba",
                            ZipCode = 7475
                        },
                        new
                        {
                            AddressId = 31,
                            Address = "Av. Mitre 9882",
                            City = "Las Leñas",
                            State = "Santa Fe",
                            ZipCode = 3036
                        },
                        new
                        {
                            AddressId = 32,
                            Address = "Juan Domingo Peron 7833",
                            City = "Palermo",
                            State = "Tucumán",
                            ZipCode = 9105
                        },
                        new
                        {
                            AddressId = 33,
                            Address = "Francisco Pienovi 8174",
                            City = "Yerba Buena",
                            State = "Santa Fe",
                            ZipCode = 3798
                        },
                        new
                        {
                            AddressId = 34,
                            Address = "Av. Los Quilmes 9566",
                            City = "Yerba Buena",
                            State = "Tucumán",
                            ZipCode = 1199
                        },
                        new
                        {
                            AddressId = 35,
                            Address = "Cochabamba 1767",
                            City = "Resistencia",
                            State = "Chaco",
                            ZipCode = 8974
                        },
                        new
                        {
                            AddressId = 36,
                            Address = "Cochabamba 3008",
                            City = "Resistencia",
                            State = "Corrientes",
                            ZipCode = 1971
                        },
                        new
                        {
                            AddressId = 37,
                            Address = "Av. Independencia 2372",
                            City = "Las Leñas",
                            State = "Salta",
                            ZipCode = 7406
                        },
                        new
                        {
                            AddressId = 38,
                            Address = "Castro Barro 5104",
                            City = "Ushuaia",
                            State = "Chaco",
                            ZipCode = 7518
                        },
                        new
                        {
                            AddressId = 39,
                            Address = "Av. Los Quilmes 2790",
                            City = "Mina Clavero",
                            State = "Entre Ríos",
                            ZipCode = 6025
                        },
                        new
                        {
                            AddressId = 40,
                            Address = "Castro Barro 6371",
                            City = "Ushuaia",
                            State = "Misiones",
                            ZipCode = 5952
                        },
                        new
                        {
                            AddressId = 41,
                            Address = "Conesa 1326",
                            City = "San Lorenzo",
                            State = "Tucumán",
                            ZipCode = 9447
                        },
                        new
                        {
                            AddressId = 42,
                            Address = "Av. Manuel Belgrano 2244",
                            City = "Resistencia",
                            State = "Salta",
                            ZipCode = 2581
                        },
                        new
                        {
                            AddressId = 43,
                            Address = "Las Heras 8730",
                            City = "La Boca",
                            State = "Misiones",
                            ZipCode = 5795
                        },
                        new
                        {
                            AddressId = 44,
                            Address = "Hiprito Yrigiyen 4235",
                            City = "La Boca",
                            State = "Tucumán",
                            ZipCode = 6034
                        },
                        new
                        {
                            AddressId = 45,
                            Address = "Cochabamba 3710",
                            City = "Bariloche",
                            State = "Misiones",
                            ZipCode = 6918
                        },
                        new
                        {
                            AddressId = 46,
                            Address = "Av. Los Quilmes 2769",
                            City = "Bariloche",
                            State = "Entre Ríos",
                            ZipCode = 9920
                        },
                        new
                        {
                            AddressId = 47,
                            Address = "Castro Barro 2704",
                            City = "Florencio Varela",
                            State = "Tucumán",
                            ZipCode = 5036
                        },
                        new
                        {
                            AddressId = 48,
                            Address = "Conesa 1694",
                            City = "Bariloche",
                            State = "Misiones",
                            ZipCode = 2280
                        },
                        new
                        {
                            AddressId = 49,
                            Address = "Francisco Pienovi 4348",
                            City = "Bariloche",
                            State = "Misiones",
                            ZipCode = 9266
                        },
                        new
                        {
                            AddressId = 50,
                            Address = "Francisco Pienovi 8577",
                            City = "La Boca",
                            State = "Misiones",
                            ZipCode = 5666
                        },
                        new
                        {
                            AddressId = 51,
                            Address = "Av. Mitre 1798",
                            City = "San Lorenzo",
                            State = "Salta",
                            ZipCode = 6308
                        },
                        new
                        {
                            AddressId = 52,
                            Address = "Cochabamba 3792",
                            City = "La Boca",
                            State = "Salta",
                            ZipCode = 4065
                        },
                        new
                        {
                            AddressId = 53,
                            Address = "Av. San Martin 8493",
                            City = "Mina Clavero",
                            State = "Tucumán",
                            ZipCode = 4943
                        },
                        new
                        {
                            AddressId = 54,
                            Address = "Av. San Martin 7056",
                            City = "Palermo",
                            State = "Misiones",
                            ZipCode = 7039
                        },
                        new
                        {
                            AddressId = 55,
                            Address = "Luis Braile 4615",
                            City = "Las Leñas",
                            State = "Santa Fe",
                            ZipCode = 4915
                        },
                        new
                        {
                            AddressId = 56,
                            Address = "Av. Los Quilmes 3540",
                            City = "Resistencia",
                            State = "Misiones",
                            ZipCode = 5184
                        },
                        new
                        {
                            AddressId = 57,
                            Address = "Av. Mitre 8212",
                            City = "Mina Clavero",
                            State = "Buenos Aires",
                            ZipCode = 7510
                        },
                        new
                        {
                            AddressId = 58,
                            Address = "Hiprito Yrigiyen 7202",
                            City = "Florencio Varela",
                            State = "Misiones",
                            ZipCode = 2097
                        },
                        new
                        {
                            AddressId = 59,
                            Address = "Francisco Pienovi 2473",
                            City = "Resistencia",
                            State = "Mendoza",
                            ZipCode = 3747
                        },
                        new
                        {
                            AddressId = 60,
                            Address = "Juan Domingo Peron 1386",
                            City = "Bariloche",
                            State = "Tucumán",
                            ZipCode = 1167
                        },
                        new
                        {
                            AddressId = 61,
                            Address = "Las Heras 1749",
                            City = "Las Leñas",
                            State = "Corrientes",
                            ZipCode = 6440
                        },
                        new
                        {
                            AddressId = 62,
                            Address = "Hiprito Yrigiyen 5528",
                            City = "Resistencia",
                            State = "Buenos Aires",
                            ZipCode = 4248
                        },
                        new
                        {
                            AddressId = 63,
                            Address = "Av. Los Quilmes 9857",
                            City = "Florencio Varela",
                            State = "Mendoza",
                            ZipCode = 2666
                        },
                        new
                        {
                            AddressId = 64,
                            Address = "Av. Cabildo 2743",
                            City = "Palermo",
                            State = "Salta",
                            ZipCode = 4720
                        },
                        new
                        {
                            AddressId = 65,
                            Address = "Francisco Pienovi 7734",
                            City = "La Boca",
                            State = "Tucumán",
                            ZipCode = 6292
                        },
                        new
                        {
                            AddressId = 66,
                            Address = "Av. Los Quilmes 2561",
                            City = "San Lorenzo",
                            State = "Misiones",
                            ZipCode = 5242
                        },
                        new
                        {
                            AddressId = 67,
                            Address = "Francisco Pienovi 4562",
                            City = "Resistencia",
                            State = "Córdoba",
                            ZipCode = 2041
                        },
                        new
                        {
                            AddressId = 68,
                            Address = "Av. Independencia 3413",
                            City = "La Boca",
                            State = "Córdoba",
                            ZipCode = 1169
                        },
                        new
                        {
                            AddressId = 69,
                            Address = "Luis Braile 5141",
                            City = "Florencio Varela",
                            State = "Corrientes",
                            ZipCode = 1251
                        },
                        new
                        {
                            AddressId = 70,
                            Address = "Castro Barro 6101",
                            City = "Resistencia",
                            State = "Mendoza",
                            ZipCode = 2446
                        },
                        new
                        {
                            AddressId = 71,
                            Address = "Av. Manuel Belgrano 6253",
                            City = "Palermo",
                            State = "Buenos Aires",
                            ZipCode = 7234
                        },
                        new
                        {
                            AddressId = 72,
                            Address = "Av. Mitre 5819",
                            City = "Florencio Varela",
                            State = "Tucumán",
                            ZipCode = 4779
                        },
                        new
                        {
                            AddressId = 73,
                            Address = "Av. Manuel Belgrano 4675",
                            City = "La Boca",
                            State = "Santa Fe",
                            ZipCode = 7717
                        },
                        new
                        {
                            AddressId = 74,
                            Address = "Av. Manuel Belgrano 5829",
                            City = "Bariloche",
                            State = "Mendoza",
                            ZipCode = 2540
                        },
                        new
                        {
                            AddressId = 75,
                            Address = "Castro Barro 7500",
                            City = "Bariloche",
                            State = "Mendoza",
                            ZipCode = 6242
                        },
                        new
                        {
                            AddressId = 76,
                            Address = "Luis Braile 1375",
                            City = "Palermo",
                            State = "Santa Fe",
                            ZipCode = 1878
                        },
                        new
                        {
                            AddressId = 77,
                            Address = "Av. Independencia 8670",
                            City = "Florencio Varela",
                            State = "Santa Fe",
                            ZipCode = 9408
                        },
                        new
                        {
                            AddressId = 78,
                            Address = "Av. San Martin 7941",
                            City = "Resistencia",
                            State = "Misiones",
                            ZipCode = 5977
                        },
                        new
                        {
                            AddressId = 79,
                            Address = "Av. Cabildo 7941",
                            City = "Las Leñas",
                            State = "Buenos Aires",
                            ZipCode = 2090
                        },
                        new
                        {
                            AddressId = 80,
                            Address = "Castro Barro 1752",
                            City = "Palermo",
                            State = "Tucumán",
                            ZipCode = 1871
                        });
                });

            modelBuilder.Entity("Domain.Entities.UserData", b =>
                {
                    b.Property<long>("CardNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CardNumber"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("BatchCardId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardNumber");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("BatchCardId");

                    b.ToTable("UserData");

                    b.HasData(
                        new
                        {
                            CardNumber = 553270770066L,
                            AddressId = 1,
                            BatchCardId = 1,
                            Name = "Maria",
                            Surname = "Rodriguez"
                        },
                        new
                        {
                            CardNumber = 857593446327L,
                            AddressId = 2,
                            BatchCardId = 1,
                            Name = "Laura",
                            Surname = "Martinez"
                        },
                        new
                        {
                            CardNumber = 899043343285L,
                            AddressId = 3,
                            BatchCardId = 1,
                            Name = "Juan",
                            Surname = "Perez"
                        },
                        new
                        {
                            CardNumber = 313787886966L,
                            AddressId = 4,
                            BatchCardId = 1,
                            Name = "Pedro",
                            Surname = "Rodriguez"
                        },
                        new
                        {
                            CardNumber = 267764218034L,
                            AddressId = 5,
                            BatchCardId = 1,
                            Name = "Lucas",
                            Surname = "Garcia"
                        },
                        new
                        {
                            CardNumber = 918132239958L,
                            AddressId = 6,
                            BatchCardId = 1,
                            Name = "Juan",
                            Surname = "Garcia"
                        },
                        new
                        {
                            CardNumber = 906124234496L,
                            AddressId = 7,
                            BatchCardId = 1,
                            Name = "Juan",
                            Surname = "Fernandez"
                        },
                        new
                        {
                            CardNumber = 549843294378L,
                            AddressId = 8,
                            BatchCardId = 1,
                            Name = "Valentina",
                            Surname = "Fernandez"
                        },
                        new
                        {
                            CardNumber = 300698625624L,
                            AddressId = 9,
                            BatchCardId = 1,
                            Name = "Carlos",
                            Surname = "Gonzalez"
                        },
                        new
                        {
                            CardNumber = 956856793169L,
                            AddressId = 10,
                            BatchCardId = 1,
                            Name = "Maria",
                            Surname = "Rodriguez"
                        },
                        new
                        {
                            CardNumber = 834090807724L,
                            AddressId = 11,
                            BatchCardId = 1,
                            Name = "Valentina",
                            Surname = "Ramirez"
                        },
                        new
                        {
                            CardNumber = 770019674918L,
                            AddressId = 12,
                            BatchCardId = 1,
                            Name = "Maria",
                            Surname = "Torres"
                        },
                        new
                        {
                            CardNumber = 747266045588L,
                            AddressId = 13,
                            BatchCardId = 1,
                            Name = "Juan",
                            Surname = "Perez"
                        },
                        new
                        {
                            CardNumber = 744355618646L,
                            AddressId = 14,
                            BatchCardId = 1,
                            Name = "Diego",
                            Surname = "Perez"
                        },
                        new
                        {
                            CardNumber = 574612039444L,
                            AddressId = 15,
                            BatchCardId = 1,
                            Name = "Pedro",
                            Surname = "Sanchez"
                        },
                        new
                        {
                            CardNumber = 254601348489L,
                            AddressId = 16,
                            BatchCardId = 1,
                            Name = "Juan",
                            Surname = "Martinez"
                        },
                        new
                        {
                            CardNumber = 709582611379L,
                            AddressId = 17,
                            BatchCardId = 1,
                            Name = "Lucas",
                            Surname = "Fernandez"
                        },
                        new
                        {
                            CardNumber = 381713195306L,
                            AddressId = 18,
                            BatchCardId = 1,
                            Name = "Juan",
                            Surname = "Ramirez"
                        },
                        new
                        {
                            CardNumber = 726381681325L,
                            AddressId = 19,
                            BatchCardId = 1,
                            Name = "Pedro",
                            Surname = "Torres"
                        },
                        new
                        {
                            CardNumber = 579819709632L,
                            AddressId = 20,
                            BatchCardId = 1,
                            Name = "Sofia",
                            Surname = "Torres"
                        },
                        new
                        {
                            CardNumber = 258332630605L,
                            AddressId = 21,
                            BatchCardId = 2,
                            Name = "Valentina",
                            Surname = "Lopez"
                        },
                        new
                        {
                            CardNumber = 587538929495L,
                            AddressId = 22,
                            BatchCardId = 2,
                            Name = "Ana",
                            Surname = "Gonzalez"
                        },
                        new
                        {
                            CardNumber = 556146222593L,
                            AddressId = 23,
                            BatchCardId = 2,
                            Name = "Maria",
                            Surname = "Ramirez"
                        },
                        new
                        {
                            CardNumber = 531709084590L,
                            AddressId = 24,
                            BatchCardId = 2,
                            Name = "Laura",
                            Surname = "Lopez"
                        },
                        new
                        {
                            CardNumber = 358110496342L,
                            AddressId = 25,
                            BatchCardId = 2,
                            Name = "Ana",
                            Surname = "Sanchez"
                        },
                        new
                        {
                            CardNumber = 928251365712L,
                            AddressId = 26,
                            BatchCardId = 2,
                            Name = "Lucas",
                            Surname = "Fernandez"
                        },
                        new
                        {
                            CardNumber = 600237656111L,
                            AddressId = 27,
                            BatchCardId = 2,
                            Name = "Valentina",
                            Surname = "Fernandez"
                        },
                        new
                        {
                            CardNumber = 910689936764L,
                            AddressId = 28,
                            BatchCardId = 2,
                            Name = "Ana",
                            Surname = "Sanchez"
                        },
                        new
                        {
                            CardNumber = 593547787312L,
                            AddressId = 29,
                            BatchCardId = 2,
                            Name = "Laura",
                            Surname = "Perez"
                        },
                        new
                        {
                            CardNumber = 958706200512L,
                            AddressId = 30,
                            BatchCardId = 2,
                            Name = "Laura",
                            Surname = "Torres"
                        },
                        new
                        {
                            CardNumber = 181540426063L,
                            AddressId = 31,
                            BatchCardId = 2,
                            Name = "Lucas",
                            Surname = "Sanchez"
                        },
                        new
                        {
                            CardNumber = 403833585950L,
                            AddressId = 32,
                            BatchCardId = 2,
                            Name = "Pedro",
                            Surname = "Torres"
                        },
                        new
                        {
                            CardNumber = 974325970789L,
                            AddressId = 33,
                            BatchCardId = 2,
                            Name = "Carlos",
                            Surname = "Garcia"
                        },
                        new
                        {
                            CardNumber = 815262160695L,
                            AddressId = 34,
                            BatchCardId = 2,
                            Name = "Laura",
                            Surname = "Rodriguez"
                        },
                        new
                        {
                            CardNumber = 704341435406L,
                            AddressId = 35,
                            BatchCardId = 2,
                            Name = "Laura",
                            Surname = "Fernandez"
                        },
                        new
                        {
                            CardNumber = 290866974482L,
                            AddressId = 36,
                            BatchCardId = 2,
                            Name = "Sofia",
                            Surname = "Rodriguez"
                        },
                        new
                        {
                            CardNumber = 625093933805L,
                            AddressId = 37,
                            BatchCardId = 2,
                            Name = "Lucas",
                            Surname = "Sanchez"
                        },
                        new
                        {
                            CardNumber = 265421080063L,
                            AddressId = 38,
                            BatchCardId = 2,
                            Name = "Valentina",
                            Surname = "Garcia"
                        },
                        new
                        {
                            CardNumber = 269091695974L,
                            AddressId = 39,
                            BatchCardId = 2,
                            Name = "Diego",
                            Surname = "Gonzalez"
                        },
                        new
                        {
                            CardNumber = 353399676642L,
                            AddressId = 40,
                            BatchCardId = 2,
                            Name = "Lucas",
                            Surname = "Rodriguez"
                        },
                        new
                        {
                            CardNumber = 569884446492L,
                            AddressId = 41,
                            BatchCardId = 3,
                            Name = "Lucas",
                            Surname = "Rodriguez"
                        },
                        new
                        {
                            CardNumber = 795174916041L,
                            AddressId = 42,
                            BatchCardId = 3,
                            Name = "Juan",
                            Surname = "Fernandez"
                        },
                        new
                        {
                            CardNumber = 304723332949L,
                            AddressId = 43,
                            BatchCardId = 3,
                            Name = "Pedro",
                            Surname = "Torres"
                        },
                        new
                        {
                            CardNumber = 486016214979L,
                            AddressId = 44,
                            BatchCardId = 3,
                            Name = "Carlos",
                            Surname = "Fernandez"
                        },
                        new
                        {
                            CardNumber = 673729540409L,
                            AddressId = 45,
                            BatchCardId = 3,
                            Name = "Pedro",
                            Surname = "Lopez"
                        },
                        new
                        {
                            CardNumber = 720382564329L,
                            AddressId = 46,
                            BatchCardId = 3,
                            Name = "Ana",
                            Surname = "Martinez"
                        },
                        new
                        {
                            CardNumber = 787764019214L,
                            AddressId = 47,
                            BatchCardId = 3,
                            Name = "Lucas",
                            Surname = "Martinez"
                        },
                        new
                        {
                            CardNumber = 164477165611L,
                            AddressId = 48,
                            BatchCardId = 3,
                            Name = "Pedro",
                            Surname = "Perez"
                        },
                        new
                        {
                            CardNumber = 953523375376L,
                            AddressId = 49,
                            BatchCardId = 3,
                            Name = "Lucas",
                            Surname = "Rodriguez"
                        },
                        new
                        {
                            CardNumber = 947504727869L,
                            AddressId = 50,
                            BatchCardId = 3,
                            Name = "Juan",
                            Surname = "Fernandez"
                        },
                        new
                        {
                            CardNumber = 496099949384L,
                            AddressId = 51,
                            BatchCardId = 3,
                            Name = "Carlos",
                            Surname = "Garcia"
                        },
                        new
                        {
                            CardNumber = 613310963768L,
                            AddressId = 52,
                            BatchCardId = 3,
                            Name = "Lucas",
                            Surname = "Sanchez"
                        },
                        new
                        {
                            CardNumber = 462527309262L,
                            AddressId = 53,
                            BatchCardId = 3,
                            Name = "Ana",
                            Surname = "Lopez"
                        },
                        new
                        {
                            CardNumber = 995847179644L,
                            AddressId = 54,
                            BatchCardId = 3,
                            Name = "Valentina",
                            Surname = "Martinez"
                        },
                        new
                        {
                            CardNumber = 503632234846L,
                            AddressId = 55,
                            BatchCardId = 3,
                            Name = "Juan",
                            Surname = "Fernandez"
                        },
                        new
                        {
                            CardNumber = 452661454269L,
                            AddressId = 56,
                            BatchCardId = 3,
                            Name = "Juan",
                            Surname = "Sanchez"
                        },
                        new
                        {
                            CardNumber = 501539115986L,
                            AddressId = 57,
                            BatchCardId = 3,
                            Name = "Laura",
                            Surname = "Fernandez"
                        },
                        new
                        {
                            CardNumber = 784701951832L,
                            AddressId = 58,
                            BatchCardId = 3,
                            Name = "Ana",
                            Surname = "Torres"
                        },
                        new
                        {
                            CardNumber = 865986979590L,
                            AddressId = 59,
                            BatchCardId = 3,
                            Name = "Laura",
                            Surname = "Perez"
                        },
                        new
                        {
                            CardNumber = 631755283106L,
                            AddressId = 60,
                            BatchCardId = 3,
                            Name = "Maria",
                            Surname = "Garcia"
                        },
                        new
                        {
                            CardNumber = 331863666435L,
                            AddressId = 61,
                            BatchCardId = 4,
                            Name = "Ana",
                            Surname = "Fernandez"
                        },
                        new
                        {
                            CardNumber = 830389386546L,
                            AddressId = 62,
                            BatchCardId = 4,
                            Name = "Pedro",
                            Surname = "Ramirez"
                        },
                        new
                        {
                            CardNumber = 336432169213L,
                            AddressId = 63,
                            BatchCardId = 4,
                            Name = "Ana",
                            Surname = "Garcia"
                        },
                        new
                        {
                            CardNumber = 858845656005L,
                            AddressId = 64,
                            BatchCardId = 4,
                            Name = "Ana",
                            Surname = "Martinez"
                        },
                        new
                        {
                            CardNumber = 359901760741L,
                            AddressId = 65,
                            BatchCardId = 4,
                            Name = "Laura",
                            Surname = "Lopez"
                        },
                        new
                        {
                            CardNumber = 946968025249L,
                            AddressId = 66,
                            BatchCardId = 4,
                            Name = "Lucas",
                            Surname = "Ramirez"
                        },
                        new
                        {
                            CardNumber = 741830617271L,
                            AddressId = 67,
                            BatchCardId = 4,
                            Name = "Ana",
                            Surname = "Rodriguez"
                        },
                        new
                        {
                            CardNumber = 532321850775L,
                            AddressId = 68,
                            BatchCardId = 4,
                            Name = "Valentina",
                            Surname = "Garcia"
                        },
                        new
                        {
                            CardNumber = 478492516795L,
                            AddressId = 69,
                            BatchCardId = 4,
                            Name = "Valentina",
                            Surname = "Ramirez"
                        },
                        new
                        {
                            CardNumber = 651370857834L,
                            AddressId = 70,
                            BatchCardId = 4,
                            Name = "Valentina",
                            Surname = "Perez"
                        },
                        new
                        {
                            CardNumber = 761643838488L,
                            AddressId = 71,
                            BatchCardId = 4,
                            Name = "Diego",
                            Surname = "Sanchez"
                        },
                        new
                        {
                            CardNumber = 912623582129L,
                            AddressId = 72,
                            BatchCardId = 4,
                            Name = "Juan",
                            Surname = "Perez"
                        },
                        new
                        {
                            CardNumber = 800108336745L,
                            AddressId = 73,
                            BatchCardId = 4,
                            Name = "Carlos",
                            Surname = "Ramirez"
                        },
                        new
                        {
                            CardNumber = 977944695362L,
                            AddressId = 74,
                            BatchCardId = 4,
                            Name = "Ana",
                            Surname = "Torres"
                        },
                        new
                        {
                            CardNumber = 636405956430L,
                            AddressId = 75,
                            BatchCardId = 4,
                            Name = "Diego",
                            Surname = "Rodriguez"
                        },
                        new
                        {
                            CardNumber = 926291640170L,
                            AddressId = 76,
                            BatchCardId = 4,
                            Name = "Juan",
                            Surname = "Gonzalez"
                        },
                        new
                        {
                            CardNumber = 654065725592L,
                            AddressId = 77,
                            BatchCardId = 4,
                            Name = "Carlos",
                            Surname = "Fernandez"
                        },
                        new
                        {
                            CardNumber = 602497354574L,
                            AddressId = 78,
                            BatchCardId = 4,
                            Name = "Carlos",
                            Surname = "Torres"
                        },
                        new
                        {
                            CardNumber = 236638206986L,
                            AddressId = 79,
                            BatchCardId = 4,
                            Name = "Valentina",
                            Surname = "Fernandez"
                        },
                        new
                        {
                            CardNumber = 783364247669L,
                            AddressId = 80,
                            BatchCardId = 4,
                            Name = "Diego",
                            Surname = "Garcia"
                        });
                });

            modelBuilder.Entity("Domain.Entities.BatchCard", b =>
                {
                    b.HasOne("Domain.Entities.BankFormat", "BankFormatNav")
                        .WithMany()
                        .HasForeignKey("BankFormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankFormatNav");
                });

            modelBuilder.Entity("Domain.Entities.UserData", b =>
                {
                    b.HasOne("Domain.Entities.UserAddress", "AddressNav")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.UserData", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.BatchCard", null)
                        .WithMany("UserDataCollection")
                        .HasForeignKey("BatchCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddressNav");
                });

            modelBuilder.Entity("Domain.Entities.BatchCard", b =>
                {
                    b.Navigation("UserDataCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
